title: "Citoyens de Centre Brou - Bourg-en-Bresse"
description: Site des conseils citoyens de Centre-Brou-Baudières à Bourg-en-Bresse
author: Bertrand Keller
lang: fr
timezone: UTC
url: "https://bertrandkeller.github.io"
baseurl: ""
destination: _static

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "citoyens"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  actions:
    output: true
    permalink: /:collection/:name
  citoyens:
    output: true
    permalink: /:collection/:name

markdown: kramdown
remote_theme: bertrandkeller/whiteglass
excerpt_separator: "<!-- more -->"

kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-default-layout

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 1

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

exclude:
  - .cache
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - script
  - vendor
  - gems
  - tmp
  - LICENSE.md
  - README.md
  - LICENSE
  - node_modules
  - index.js
  - package.json
  - vercel.json



