name: GitHub Pages publication
# https://github.com/jeffreytse/jekyll-deploy-action

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Specify the target branch (optional)
    # - uses: bertrandkeller/jekyll-action@v2
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     target_branch: 'pages'
    #     jekyll_src: ''

    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --path=vendor/bundle --jobs 4 --retry 3
        bundle clean

    - name: ls
      run: ls

    - name: jekyll build
      run: JEKYLL_ENV=production bundle exec jekyll build --destination _static

    - name: ls
      run: ls

    - name: ls
      run: |
        cd _static
        ls
        cd citoyens
        ls

    - name: push pages
      run: |
        ls
        git config user.name "${GITHUB_ACTOR}" && \
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
        git add . && \
        git commit -m "jekyll build from Action ${GITHUB_SHA}" && \
        git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git main:pages
